### ISSUE TITLE
User causes port number parsing error, crash on start

### ISSUE THREAD

**Issue by jjblum** [platypusllc/server#45]
If a user accidentally adds a space to the port number option, the phone cannot parse this correctly and will crash on start up. The user cannot manually change this back due to the crash behavior. If the user clear's the apps data in the phone's settings, the port goes back to the default and it stops crashing, but now the options have all been reset. Including the Firebase key.

It would be better if port number parsing errors were handled such that the default port number was used and a warning popped up. Or consider trimming spaces.

**Comment by christomaszewski** [comment]
Resolved by commit #47
