### ISSUE TITLE
JSONArray is not compatible with API 17 

### ISSUE THREAD

**Issue by Zeshengx** [platypusllc/server#5]
One touch server crashed on Samsung mini3, running API 17, when starting waypoints. The error is in:
VehicleServerImpl.java#L695. `try {
                mLogger.info(new JSONObject()
                        .put("nav", new JSONObject()
                                .put("controller", controller)
                                .put("waypoints", new JSONArray(waypoints))));`

**Comment by psigen** [comment]
This is because the array constructor function for `JSONArray()` was only added in API 19:
https://github.com/socketio/socket.io-client-java/issues/10

Do we really need to support APIs lower than 19?  If so, we need to implement a for-loop that recreates this constructor.

**Comment by psigen** [comment]
We are solving this issue by **requiring** API 21 or newer.
